# Generated by Django 4.2.22 on 2025-06-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileapp', '0003_filemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='s3_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
