#!/bin/bash
exec > /tmp/user-data.log 2>&1
echo "Starting user-data script..."

# Install git and clone your project
sudo yum install -y git
sudo -u ec2-user git clone -b master --single-branch https://github.com/Birendrakum/AWS-Project.git /home/ec2-user/AWS-Project

# Install Python3, pip, and jq (needed for JSON parsing)
sudo yum install -y python3 python3-pip jq

# Install Django and other Python packages
sudo -H pip3 install django boto3 django-storages[boto3]

# Install nginx
sudo yum install -y nginx

# Go to the AWS-Project directory
cd /home/ec2-user/AWS-Project

# First, retrieve a token from the metadata service with a 6-hour TTL
TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
# Then, use the token to fetch the public IP
PUBLIC_IP=$(curl -s -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/public-ipv4)
echo "Public IP: $PUBLIC_IP"

sudo sed -i "s/server_name .*;/server_name $PUBLIC_IP;/g" django.conf

# Copy the updated django.conf to the nginx configuration directory
sudo cp django.conf /etc/nginx/conf.d/

# Restart nginx to load the new configuration
sudo systemctl restart nginx

# Navigate to the Django project directory
cd webpage_code/

# Fetch AWS secrets from Secrets Manager (replace "secret1" with your secret's ID)
SECRET_JSON=$(aws secretsmanager get-secret-value --secret-id "secret1" --query "SecretString" --output text)

# Parse the secret JSON to get individual keys
ACCESS_KEY=$(echo $SECRET_JSON | jq -r '.Access_key')
SECRET_KEY=$(echo $SECRET_JSON | jq -r '.Secret_key')

# Inject the retrieved keys into your Django settings.py file
sudo sed -i "s/^AWS_ACCESS_KEY_ID\s*=.*/AWS_ACCESS_KEY_ID = '$ACCESS_KEY'/" /home/ec2-user/AWS-Project/Webpage_code/myproject/settings.py
sudo sed -i "s/^AWS_SECRET_ACCESS_KEY\s*=.*/AWS_SECRET_ACCESS_KEY = '$SECRET_KEY'/" /home/ec2-user/AWS-Project/Webpage_code/myproject/settings.py


# Apply Django migrations and start the Django server binding to all network interfaces
python3 manage.py makemigrations
python3 manage.py migrate
python3 manage.py runserver 0.0.0.0:8000

echo "Setup complete. Access your website using http://$PUBLIC_IP:8000"
